### PR TITLE
Updating the Spree::Product query to use `where`

### LINKED ISSUE #4: undefined method `active` for #<Class> in solidus_defaults.rb:26
Looks like the `active` scope has been removed from Spree::Product in Solidus 2.1.  I'll make up a PR.

### PR DESCRIPTION
**Pull request by funwhilelost**
This removes the dependency on the deprecated `active` scope and will fix #4 - replacing it with `.where(deleted_at: nil).where('available_on > ?', DateTime.now)` which matches the new schema.

### CODE REVIEW

**Comment by MobilUser** [comment]
when will this PR merged as without the sitemap generation will not work with Solidus 2.1

**Comment by jhawthorn** [comment]
Thanks. This should be fixed by #6
